//! Byte-for-byte parity of the `"xml"` output format against the reference
//! normalized XML files generated by libmbus (rSCADA) in
//! `tests/rscada/test-frames/*.norm.xml`.
//!
//! Frames listed in `KNOWN_MISMATCHES` currently render differently from
//! libmbus; the test fails if one of them starts matching so the list ratchets
//! down as the parser gains parity.
#![cfg(feature = "std")]
#![allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]

use std::fs;
use std::path::PathBuf;

/// Frames that do not yet match libmbus's normalized XML output.
///
/// All remaining entries fail because the parser rejects BCD data containing
/// non-decimal digits (the `Fh` negative sign marker and manufacturer error
/// markers like `DDh`), aborting the record stream, while libmbus decodes
/// them with its lenient BCD algorithm.
const KNOWN_MISMATCHES: &[&str] = &[
    "ELS_Elster-F96-Plus",
    "SLB_CF-Compact-Integral-MK-MaXX",
    "abb_f95",
    "landis+gyr_ultraheat_t230",
    // The frames below additionally require the `plaintext-before-extension`
    // feature: their meters emit the plaintext VIF directly after the VIF
    // byte (libmbus semantics) instead of after the VIFE chain.
    #[cfg(not(feature = "plaintext-before-extension"))]
    "ACW_Itron-CYBLE-M-Bus-14",
    #[cfg(not(feature = "plaintext-before-extension"))]
    "EDC",
    #[cfg(not(feature = "plaintext-before-extension"))]
    "ELV-Elvaco-CMa10",
    #[cfg(not(feature = "plaintext-before-extension"))]
    "THI_cma10",
    #[cfg(not(feature = "plaintext-before-extension"))]
    "elv_temp_humid",
    #[cfg(not(feature = "plaintext-before-extension"))]
    "itron_cyble_m-bus_v1.4_cold_water",
    #[cfg(not(feature = "plaintext-before-extension"))]
    "itron_cyble_m-bus_v1.4_gas",
    #[cfg(not(feature = "plaintext-before-extension"))]
    "itron_cyble_m-bus_v1.4_water",
];

fn first_difference(expected: &str, actual: &str) -> String {
    for (line_number, (expected_line, actual_line)) in expected
        .lines()
        .map(Some)
        .chain(std::iter::repeat(None))
        .zip(actual.lines().map(Some).chain(std::iter::repeat(None)))
        .enumerate()
    {
        if expected_line == actual_line {
            continue;
        }
        return format!(
            "line {}:\n  expected: {}\n  actual:   {}",
            line_number + 1,
            expected_line.unwrap_or("<missing>"),
            actual_line.unwrap_or("<missing>")
        );
    }
    "no line-level difference (whitespace or trailing content)".to_string()
}

#[test]
fn xml_output_matches_libmbus_normalized_xml() {
    let dir = PathBuf::from("tests/rscada/test-frames");
    let mut hex_files: Vec<PathBuf> = fs::read_dir(&dir)
        .expect("test-frames directory")
        .filter_map(|entry| entry.ok())
        .map(|entry| entry.path())
        .filter(|path| path.extension().is_some_and(|ext| ext == "hex"))
        .collect();
    hex_files.sort();
    assert!(!hex_files.is_empty(), "no test frames found");

    let mut matching = 0;
    let mut failures = Vec::new();
    let mut fixed = Vec::new();

    for hex_path in hex_files {
        let norm_path = hex_path.with_extension("norm.xml");
        if !norm_path.exists() {
            continue;
        }
        let name = hex_path.file_stem().unwrap().to_string_lossy().into_owned();
        let input = fs::read_to_string(&hex_path).unwrap();
        let expected = fs::read_to_string(&norm_path).unwrap();
        let actual = m_bus_parser::serialize_mbus_data(&input, "xml", None);
        let known_mismatch = KNOWN_MISMATCHES.contains(&name.as_str());

        if actual == expected {
            matching += 1;
            if known_mismatch {
                fixed.push(name);
            }
        } else if !known_mismatch {
            failures.push(format!(
                "{}: {}",
                name,
                first_difference(&expected, &actual)
            ));
        }
    }

    println!(
        "libmbus XML parity: {} matching, {} known mismatches",
        matching,
        KNOWN_MISMATCHES.len()
    );

    assert!(
        failures.is_empty(),
        "XML output diverged from libmbus reference for {} frame(s):\n{}",
        failures.len(),
        failures.join("\n")
    );
    assert!(
        fixed.is_empty(),
        "frames now match libmbus, remove them from KNOWN_MISMATCHES: {:?}",
        fixed
    );
}
