//! Byte-for-byte parity of the `"xml"` output format against the reference
//! normalized XML files generated by libmbus (rSCADA) in
//! `tests/rscada/test-frames/*.norm.xml`.
//!
//! Frames listed in `KNOWN_MISMATCHES` currently render differently from
//! libmbus; the test fails if one of them starts matching so the list ratchets
//! down as the parser gains parity.
#![cfg(feature = "std")]
#![allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]

use std::fs;
use std::path::PathBuf;
use std::str::FromStr;

#[cfg(feature = "decryption")]
use m_bus_parser::DecodeOptions;
use m_bus_parser::{render_hex, OutputFormat, RenderOptions};

/// Frames that do not yet match libmbus's normalized XML output.
///
/// All remaining entries fail because the parser rejects BCD data containing
/// non-decimal digits (the `Fh` negative sign marker and manufacturer error
/// markers like `DDh`), aborting the record stream, while libmbus decodes
/// them with its lenient BCD algorithm.
const KNOWN_MISMATCHES: &[&str] = &[
    "ELS_Elster-F96-Plus",
    "SLB_CF-Compact-Integral-MK-MaXX",
    "abb_f95",
    "landis+gyr_ultraheat_t230",
    // The frames below additionally require the `plaintext-before-extension`
    // feature: their meters emit the plaintext VIF directly after the VIF
    // byte (libmbus semantics) instead of after the VIFE chain.
    #[cfg(not(feature = "plaintext-before-extension"))]
    "ELV-Elvaco-CMa10",
    #[cfg(not(feature = "plaintext-before-extension"))]
    "THI_cma10",
    #[cfg(not(feature = "plaintext-before-extension"))]
    "elv_temp_humid",
];

fn first_difference(expected: &str, actual: &str) -> String {
    for (line_number, (expected_line, actual_line)) in expected
        .lines()
        .map(Some)
        .chain(std::iter::repeat(None))
        .zip(actual.lines().map(Some).chain(std::iter::repeat(None)))
        .enumerate()
    {
        if expected_line == actual_line {
            continue;
        }
        return format!(
            "line {}:\n  expected: {}\n  actual:   {}",
            line_number + 1,
            expected_line.unwrap_or("<missing>"),
            actual_line.unwrap_or("<missing>")
        );
    }
    "no line-level difference (whitespace or trailing content)".to_string()
}

#[test]
fn xml_output_matches_libmbus_normalized_xml() {
    let dir = PathBuf::from("tests/rscada/test-frames");
    let mut hex_files: Vec<PathBuf> = fs::read_dir(&dir)
        .expect("test-frames directory")
        .filter_map(|entry| entry.ok())
        .map(|entry| entry.path())
        .filter(|path| path.extension().is_some_and(|ext| ext == "hex"))
        .collect();
    hex_files.sort();
    assert!(!hex_files.is_empty(), "no test frames found");

    let mut matching = 0;
    let mut failures = Vec::new();
    let mut fixed = Vec::new();

    for hex_path in hex_files {
        let norm_path = hex_path.with_extension("norm.xml");
        if !norm_path.exists() {
            continue;
        }
        let name = hex_path.file_stem().unwrap().to_string_lossy().into_owned();
        let input = fs::read_to_string(&hex_path).unwrap();
        let expected = fs::read_to_string(&norm_path).unwrap();
        let actual = m_bus_parser::serialize_mbus_data(&input, "xml", None);
        let known_mismatch = KNOWN_MISMATCHES.contains(&name.as_str());

        if actual == expected {
            matching += 1;
            if known_mismatch {
                fixed.push(name);
            }
        } else if !known_mismatch {
            failures.push(format!(
                "{}: {}",
                name,
                first_difference(&expected, &actual)
            ));
        }
    }

    println!(
        "libmbus XML parity: {} matching, {} known mismatches",
        matching,
        KNOWN_MISMATCHES.len()
    );

    assert!(
        failures.is_empty(),
        "XML output diverged from libmbus reference for {} frame(s):\n{}",
        failures.len(),
        failures.join("\n")
    );
    assert!(
        fixed.is_empty(),
        "frames now match libmbus, remove them from KNOWN_MISMATCHES: {:?}",
        fixed
    );
}

#[test]
fn wireless_short_transport_xml_uses_link_identity_and_transport_fields() {
    let input = concat!(
        "18 44 AE 4C 44 55 22 33 68 07 ",
        "7A 55 00 00 00 04 13 89 E2 01 00 02 3B 00 00"
    );
    let xml = render_hex(input, OutputFormat::Xml, &RenderOptions::default())
        .expect("wireless short-transport XML");

    assert!(xml.starts_with("<?xml version=\"1.0\" encoding=\"ISO-8859-1\"?>"));
    assert!(xml.contains("<Id>33225544</Id>"));
    assert!(xml.contains("<Manufacturer>SEN</Manufacturer>"));
    assert!(xml.contains("<Medium>Water</Medium>"));
    assert!(xml.contains("<AccessNumber>85</AccessNumber>"));
    assert!(xml.contains("<Status>00</Status>"));
    assert!(xml.contains("<Signature>0000</Signature>"));
    assert!(xml.contains("<DataRecord id=\"0\">"));
}

#[test]
fn wireless_ell_xml_uses_real_ell_access_without_inventing_tpl_fields() {
    let input = "12 44 AE 0C 78 56 34 12 01 07 8C 20 27 78 0B 13 43 65 87";
    let xml = render_hex(
        input,
        OutputFormat::from_str("xml").unwrap(),
        &RenderOptions::default(),
    )
    .expect("wireless ELL XML");

    assert!(xml.contains("<Id>12345678</Id>"));
    assert!(xml.contains("<Manufacturer>CEN</Manufacturer>"));
    assert!(xml.contains("<AccessNumber>39</AccessNumber>"));
    assert!(!xml.contains("<Status>"));
    assert!(!xml.contains("<Signature>"));
    assert!(xml.contains("<DataRecord id=\"0\">"));
}

#[cfg(feature = "decryption")]
#[test]
fn wireless_encrypted_xml_is_header_only_without_key_and_decodes_with_key() {
    let input = concat!(
        "2E44931578563412330333637A2A002025",
        "5923C95AAA26D1B2E7493BC2AD013EC4",
        "A6F6D3529B520EDFF0EA6DEFC955B29D",
        "6D69EBF3EC8A"
    );
    let without_key = render_hex(input, OutputFormat::Xml, &RenderOptions::default())
        .expect("encrypted wireless XML header");
    assert!(without_key.contains("<Id>12345678</Id>"));
    assert!(!without_key.contains("<DataRecord"));

    let with_key = render_hex(
        input,
        OutputFormat::Xml,
        &RenderOptions {
            decode: DecodeOptions {
                key: Some([
                    0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0A, 0x0B, 0x0C, 0x0D,
                    0x0E, 0x0F, 0x11,
                ]),
                include_enrichment: true,
            },
            ..RenderOptions::default()
        },
    )
    .expect("decrypted wireless XML");
    assert!(with_key.contains("<DataRecord id=\"0\">"));
    assert!(with_key.contains("<Value>"));
}
