// Translation of libmbus XML unit names to the public DIF/VIF model.
// XML omits orthogonal VIFE modifiers, so callers compare the base label and unit prefix.
use m_bus_parser::user_data::value_information::{Unit, UnitName::*, ValueLabel, ValueLabel::*};

pub fn unit(name: &str) -> (isize, Option<ValueLabel>, Vec<Unit>) {
    let (scale, label, units): (
        _,
        _,
        &[(m_bus_parser::user_data::value_information::UnitName, i32)],
    ) = match name {
        "1e-1  A" => (-1, Some(Current), &[(Ampere, 1)]),
        "1e-1  V" => (-1, Some(Voltage), &[(Volt, 1)]),
        "1e-2  %RH" => (-2, Some(PlainText), &[]),
        "1e-2  V" => (-2, Some(Voltage), &[(Volt, 1)]),
        "Actuality Duration (seconds)" => (0, Some(ActualityDuration), &[(Second, 1)]),
        "Averaging Duration (hours)" => (0, Some(AveragingDuration), &[(Hour, 1)]),
        "Averaging Duration (minutes)" => (0, Some(AveragingDuration), &[(Minute, 1)]),
        "Averaging Duration (seconds)" => (0, Some(AveragingDuration), &[(Second, 1)]),
        "C" => (0, Some(PlainText), &[]),
        "Customer location" => (0, Some(CustomerLocation), &[]),
        "Digital input (binary)" => (0, Some(DigitalInput), &[]),
        "Digital output (binary)" => (0, Some(DigitalOutput), &[]),
        "Energy (0.1 MWh)" => (5, Some(Energy), &[(Watt, 1), (Hour, 1)]),
        "Energy (10 Wh)" => (1, Some(Energy), &[(Watt, 1), (Hour, 1)]),
        "Energy (10 kWh)" => (4, Some(Energy), &[(Watt, 1), (Hour, 1)]),
        "Energy (100 Wh)" => (2, Some(Energy), &[(Watt, 1), (Hour, 1)]),
        "Energy (MJ)" => (6, Some(Energy), &[(Joul, 1)]),
        "Energy (Wh)" => (0, Some(Energy), &[(Watt, 1), (Hour, 1)]),
        "Energy (kWh)" => (3, Some(Energy), &[(Watt, 1), (Hour, 1)]),
        "Energy (mWh)" => (-3, Some(Energy), &[(Watt, 1), (Hour, 1)]),
        "Error flags" => (0, Some(ErrorFlags), &[]),
        "External temperature ( deg C)" => (0, Some(ExternalTemperature), &[(Celsius, 1)]),
        "External temperature (1e-2  deg C)" => (-2, Some(ExternalTemperature), &[(Celsius, 1)]),
        "Fabrication number" => (0, Some(FabricationNumber), &[]),
        "Firmware version" => (0, Some(MetrologyFirmwareVersion), &[]),
        "Flow temperature (1e-1 deg C)" => (-1, Some(FlowTemperature), &[(Celsius, 1)]),
        "Flow temperature (1e-2 deg C)" => (-2, Some(FlowTemperature), &[(Celsius, 1)]),
        "Flow temperature (deg C)" => (0, Some(FlowTemperature), &[(Celsius, 1)]),
        "Manufacturer specific" => (0, Some(ManufacturerSpecific), &[]),
        "Medium (as in fixed header)" => (0, Some(DeviceType), &[]),
        "Model / Version" => (0, Some(ModelOrVersion), &[]),
        "On time (days)" => (0, Some(OnTime), &[(Day, 1)]),
        "On time (hours)" => (0, Some(OnTime), &[(Hour, 1)]),
        "On time (seconds)" => (0, Some(OnTime), &[(Second, 1)]),
        "Operating time (days)" => (0, Some(OperatingTime), &[(Day, 1)]),
        "Operating time (hours)" => (0, Some(OperatingTime), &[(Hour, 1)]),
        "Operating time (seconds)" => (0, Some(OperatingTime), &[(Second, 1)]),
        "Parameter set identification" => (0, Some(ParameterSetIdentification), &[]),
        "Power (10 W)" => (1, Some(Power), &[(Watt, 1)]),
        "Power (100 W)" => (2, Some(Power), &[(Watt, 1)]),
        "Power (1e-1 W)" => (-1, Some(Power), &[(Watt, 1)]),
        "Power (W)" => (0, Some(Power), &[(Watt, 1)]),
        "Power (kW)" => (3, Some(Power), &[(Watt, 1)]),
        "Reserved VIF extension" => (0, Some(ValueLabel::Reserved), &[]),
        "Reset counter" => (0, Some(ResetCounter), &[]),
        "Return temperature (1e-1 deg C)" => (-1, Some(ReturnTemperature), &[(Celsius, 1)]),
        "Return temperature (1e-2 deg C)" => (-2, Some(ReturnTemperature), &[(Celsius, 1)]),
        "Return temperature (deg C)" => (0, Some(ReturnTemperature), &[(Celsius, 1)]),
        "Software version" => (0, Some(OtherSoftwareVersion), &[]),
        "Special supplier information" => (0, Some(SpecialSupplierInformation), &[]),
        "Temperature Difference ( deg C)" => (0, Some(TemperatureDifference), &[(Kelvin, 1)]),
        "Temperature Difference (1e-1  deg C)" => (-1, Some(TemperatureDifference), &[(Kelvin, 1)]),
        "Temperature Difference (1e-2  deg C)" => (-2, Some(TemperatureDifference), &[(Kelvin, 1)]),
        "Temperature Difference (m deg C)" => (-3, Some(TemperatureDifference), &[(Kelvin, 1)]),
        "Time Point (date)" => (0, Some(Date), &[]),
        "Time Point (time & date)" => (0, Some(DateTime), &[]),
        "Units for H.C.A." => (0, Some(DimensionlessHCA), &[]),
        "Unknown (VIF=0x79)" => (0, Some(EnhancedIdentification), &[]),
        "Unknown (VIF=0x7B)" => (0, None, &[]),
        "V" => (0, Some(Voltage), &[(Volt, 1)]),
        "Volume ( m^3)" => (0, Some(Volume), &[(Meter, 3)]),
        "Volume (1e-1  m^3)" => (-1, Some(Volume), &[(Meter, 3)]),
        "Volume (1e-2  m^3)" => (-2, Some(Volume), &[(Meter, 3)]),
        "Volume (1e-4  m^3)" => (-4, Some(Volume), &[(Meter, 3)]),
        "Volume (m m^3)" => (-3, Some(Volume), &[(Meter, 3)]),
        "Volume (my m^3)" => (-6, Some(Volume), &[(Meter, 3)]),
        "Volume flow ( m^3/h)" => (0, Some(VolumeFlow), &[(Meter, 3), (Hour, -1)]),
        "Volume flow (1e-1  m^3/h)" => (-1, Some(VolumeFlow), &[(Meter, 3), (Hour, -1)]),
        "Volume flow (1e-2  m^3/h)" => (-2, Some(VolumeFlow), &[(Meter, 3), (Hour, -1)]),
        "Volume flow (1e-4  m^3/h)" => (-4, Some(VolumeFlow), &[(Meter, 3), (Hour, -1)]),
        "Volume flow (m m^3/h)" => (-3, Some(VolumeFlow), &[(Meter, 3), (Hour, -1)]),
        "bat. time" => (0, Some(PlainText), &[]),
        "c" => (0, Some(PlainText), &[]),
        "cust. ID" => (0, Some(PlainText), &[]),
        "dimensionless / no VIF" => (0, Some(Dimensionless), &[]),
        "m A" => (-3, Some(Current), &[(Ampere, 1)]),
        _ => panic!("unmapped XML unit: {name}"),
    };
    (
        scale,
        label,
        units
            .iter()
            .map(|&(name, exponent)| Unit { name, exponent })
            .collect(),
    )
}
